// AHBA Console — QA AUDIT page module. Loaded by index.html (production) and qa-demo.html (dry run). Mount-only.
(function (root) {
  'use strict';
  var Core = root.QaCore;
  var CSS = '.cq{font:13px "DM Sans",system-ui,sans-serif;color:#0e2b27}.cq-tabs{display:flex;gap:6px;margin:0 0 12px;flex-wrap:wrap}.cq-tabs button{padding:8px 14px;border-radius:10px;border:1px solid #cfe0d8;background:#fff;font-weight:700}.cq-tabs button.on{background:#0d3b34;color:#fff;border-color:#0d3b34}' +
    '.cq-stats{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px}.cq-stat{background:#fff;border:1px solid #e3e8e2;border-radius:12px;padding:10px 14px;min-width:120px}.cq-stat span{display:block;font-size:10px;color:#8a9894;text-transform:uppercase;letter-spacing:.06em}.cq-stat strong{font-size:20px}.cq-stat.warn strong{color:#c2503a}' +
    '.cq-bar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-bottom:10px}.cq-bar input,.cq-bar select{padding:7px 9px;border:1px solid #cfd8d3;border-radius:9px;font-size:12px}.cq-btn{padding:7px 12px;border-radius:9px;border:1px solid #0d3b34;background:#0d3b34;color:#fff;font-weight:700;font-size:12px;cursor:pointer}.cq-btn.ghost{background:#fff;color:#0d3b34}.cq-btn.warn{background:#c2503a;border-color:#c2503a}.cq-btn[disabled]{opacity:.5;cursor:default}' +
    '.cq table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e3e8e2;border-radius:12px;overflow:hidden}.cq th{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:#8a9894;text-align:left;padding:8px 10px;border-bottom:1px solid #e3e8e2;background:#f8f9f7}.cq td{padding:8px 10px;border-bottom:1px solid #f0f2ef;font-size:12px;vertical-align:top}.cq tr:hover td{background:#f8faf8}' +
    '.cq-pill{display:inline-block;font-size:10px;font-weight:800;padding:2px 8px;border-radius:9px;background:#eef2ec;color:#3a4a45}.cq-pill.queued{background:#fff3d6;color:#9a6200}.cq-pill.assigned{background:#e8ecff;color:#2d3fa8}.cq-pill.in_progress{background:#ffe9d6;color:#a04a00}.cq-pill.done{background:#e7f7ef;color:#11825f}.cq-pill.pool{background:#f1f1f1;color:#777}.cq-pill.fail{background:#fde4df;color:#c2503a}' +
    '.cq-age{font-size:10px;color:#8a9894}.cq-age.late{color:#c2503a;font-weight:800}.cq-map{height:320px;border-radius:12px;border:1px solid #e3e8e2;margin-bottom:12px;background:#eef2ec}.cq-cols{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}.cq-col{background:#fff;border:1px solid #e3e8e2;border-radius:12px;padding:10px}.cq-col h4{margin:0 0 8px;font-size:13px}.cq-row{border:1px solid #f0f2ef;border-radius:9px;padding:7px 9px;margin-bottom:6px;font-size:12px}' +
    '.cq-modal{position:fixed;inset:0;background:rgba(8,28,24,.45);z-index:9000;display:flex;align-items:center;justify-content:center;padding:20px}.cq-modal>div{background:#fff;border-radius:14px;max-width:920px;width:100%;max-height:92vh;overflow:auto;padding:20px}.cq-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:8px;font-size:12px}.cq-grid b{display:block;font-size:10px;color:#8a9894;text-transform:uppercase}.cq-thumbs{display:flex;gap:8px;flex-wrap:wrap}.cq-thumbs img{width:110px;height:110px;object-fit:cover;border-radius:9px;border:1px solid #e3e8e2}.cq-sec{font:800 10px Manrope,system-ui;letter-spacing:.08em;text-transform:uppercase;color:#107b5e;margin:14px 0 6px}.cq-banner{background:#fde4df;color:#8a2c1b;border:1px solid #f0c4b9;border-radius:10px;padding:8px 12px;margin-bottom:10px;font-size:12px}.cq-empty{padding:26px;text-align:center;color:#9aa6a2}';
  var COLORS = ['#18a57b', '#2d3fa8', '#c2503a', '#9a6200', '#7b2d8a', '#0d7c9a'];
  function esc(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function (c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]; }); }
  function today() { return new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Manila' }); }
  function addDays(d, n) { var x = new Date(d + 'T00:00:00+08:00'); x.setDate(x.getDate() + n); return x.toLocaleDateString('en-CA', { timeZone: 'Asia/Manila' }); }
  function daysSince(d) { return d ? Math.max(0, Math.round((new Date(today()) - new Date(d)) / 86400000)) : 0; }
  function fmtWhen(s) { return s ? new Date(s).toLocaleString('en-PH', { timeZone: 'Asia/Manila', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }) : '—'; }
  function pill(s) { return '<span class="cq-pill ' + esc(s) + '">' + esc(String(s || '').replace('_', ' ')) + '</span>'; }
  function peso(n) { return '₱' + Number(n || 0).toLocaleString('en-PH'); }

  function mount(rootEl, o) {
    var api = o.api, user = o.user || {}, deps = o.deps || {}, canEdit = deps.canEdit !== false, L = deps.L || root.L;
    var toast = deps.toast || function (m) { console.log('[cq]', m); };
    var S = { tab: 'queue', cfg: null, inspectors: [], sel: {}, filter: { status: ['queued'], page: 1 }, boardDate: today(), map: null, layer: null, unsub: null, submittedToday: 0, results: { page: 1 }, report: { from: addDays(today(), -6), to: today() } };
    if (!document.getElementById('cqCss')) { var st = document.createElement('style'); st.id = 'cqCss'; st.textContent = CSS; document.head.appendChild(st); }
    rootEl.innerHTML = '<div class="cq"><div id="cqBanner"></div><div class="cq-tabs">' + [['queue', 'Queue'], ['board', "Today's board"], ['results', 'Results'], ['reports', 'Reports'], ['settings', 'Settings']].map(function (t) { return '<button data-tab="' + t[0] + '" class="' + (t[0] === 'queue' ? 'on' : '') + '">' + t[1] + '</button>'; }).join('') + '</div><div id="cqBody"></div></div><div id="cqModal"></div>';
    var $ = function (s) { return rootEl.querySelector(s); };
    rootEl.querySelectorAll('.cq-tabs button').forEach(function (b) { b.onclick = function () { S.tab = b.dataset.tab; rootEl.querySelectorAll('.cq-tabs button').forEach(function (x) { x.classList.toggle('on', x === b); }); render(); }; });

    function load() { return Promise.all([api.getConfig(), api.listInspectors(), api.syncStatus()]).then(function (r) { S.cfg = r[0]; S.inspectors = r[1]; S.sync = r[2]; banner(); }); }
    function banner() {
      var b = $('#cqBanner'), msgs = [];
      var last = S.sync && S.sync.last_sync_at ? (Date.now() - new Date(S.sync.last_sync_at)) / 3600000 : null;
      if (last == null) msgs.push('Sheet sync has never run — install the Apps Script or upload a CSV in Settings.');
      else if (last > 2) msgs.push('Sheet sync is ' + Math.round(last) + ' h old — check the Apps Script trigger.');
      if (S.sync && S.sync.unmapped && S.sync.unmapped.length) msgs.push('Unmapped contractor name(s) in the sheet: ' + S.sync.unmapped.join(', ') + ' — map them in Settings.');
      b.innerHTML = msgs.map(function (m) { return '<div class="cq-banner">⚠ ' + esc(m) + '</div>'; }).join('');
    }
    function render() { var f = TABS[S.tab]; if (f) f(); }
    function modal(html) { $('#cqModal').innerHTML = '<div class="cq-modal"><div>' + html + '</div></div>'; $('#cqModal .cq-modal').onclick = function (e) { if (e.target === this) closeModal(); }; }
    function closeModal() { $('#cqModal').innerHTML = ''; }
    function inspectorOpts(sel) { return S.inspectors.map(function (i) { return '<option value="' + esc(i.username) + '"' + (i.username === sel ? ' selected' : '') + '>' + esc(i.username + (i.display_name ? ' · ' + i.display_name : '')) + '</option>'; }).join(''); }
    function contractorOpts() { return '<option value="">All contractors</option>' + S.cfg.contractors.map(function (c) { return '<option value="' + esc(c.sheet_name) + '">' + esc(c.display_name) + ' (' + esc(c.kind) + ')</option>'; }).join(''); }

    // ---------------- QUEUE ----------------
    function renderQueue() {
      var f = S.filter;
      $('#cqBody').innerHTML = '<div class="cq-stats" id="cqQStats"></div><div class="cq-bar">' +
        '<select id="qf_status"><option value="queued">Queued (to assign)</option><option value="pool">Pool (in-house, not selected)</option><option value="assigned">Assigned</option><option value="queued,assigned,in_progress">All open</option></select>' +
        '<select id="qf_contractor">' + contractorOpts() + '</select><select id="qf_kind"><option value="">Subcon + in-house</option><option value="subcon">Subcon only</option><option value="inhouse">In-house only</option></select>' +
        '<input type="date" id="qf_from" title="JO closed from"><input type="date" id="qf_to" title="JO closed to"><input id="qf_q" placeholder="Search name / address / JO / acct" style="min-width:220px"><button class="cq-btn ghost" id="qf_go">Filter</button>' +
        (canEdit ? '<span style="flex:1"></span><button class="cq-btn" id="q_assign" disabled>Assign selected</button><button class="cq-btn ghost" id="q_pick" disabled>Queue selected (manual pick)</button><button class="cq-btn ghost" id="q_unassign" disabled>Unassign selected</button><button class="cq-btn ghost" id="q_sample">Random sample in-house…</button>' : '') +
        '</div><div id="cqQTable"></div><div class="cq-bar" style="justify-content:flex-end"><button class="cq-btn ghost" id="q_prev">‹ Prev</button><span id="q_page"></span><button class="cq-btn ghost" id="q_next">Next ›</button></div>';
      $('#qf_status').value = f.status.join(','); if (f.contractor) $('#qf_contractor').value = f.contractor; if (f.kind) $('#qf_kind').value = f.kind; if (f.from) $('#qf_from').value = f.from; if (f.to) $('#qf_to').value = f.to; if (f.q) $('#qf_q').value = f.q;
      $('#qf_go').onclick = function () { S.filter = { status: $('#qf_status').value.split(','), contractor: $('#qf_contractor').value, kind: $('#qf_kind').value, from: $('#qf_from').value, to: $('#qf_to').value, q: $('#qf_q').value, page: 1 }; S.sel = {}; loadQueue(); };
      $('#qf_q').onkeydown = function (e) { if (e.key === 'Enter') $('#qf_go').click(); };
      $('#q_prev').onclick = function () { if (S.filter.page > 1) { S.filter.page--; loadQueue(); } };
      $('#q_next').onclick = function () { S.filter.page++; loadQueue(); };
      if (canEdit) { $('#q_assign').onclick = assignDialog; $('#q_pick').onclick = function () { act(api.queuePool(selIds(), { by: user.username }), 'queued'); }; $('#q_unassign').onclick = function () { act(api.unassignAudits(selIds(), { by: user.username }), 'unassigned'); }; $('#q_sample').onclick = sampleDialog; }
      loadQueue(); loadQueueStats();
    }
    function selIds() { return Object.keys(S.sel).filter(function (k) { return S.sel[k]; }); }
    function act(p, verb) { p.then(function (n) { toast(n + ' audit(s) ' + verb); S.sel = {}; loadQueue(); loadQueueStats(); }).catch(function (e) { toast('Failed: ' + e.message); }); }
    function loadQueueStats() {
      var m = today().slice(0, 7) + '-01';
      Promise.all([api.listAudits({ kind: 'subcon', from: m, pageSize: 1 }), api.listAudits({ kind: 'subcon', status: ['done'], from: m, pageSize: 1 }), api.listAudits({ status: ['queued'], pageSize: 1000 }), api.listAudits({ status: ['assigned', 'in_progress'], pageSize: 1 })]).then(function (r) {
        var buckets = { '0-7': 0, '8-14': 0, '15-30': 0, '31+': 0 }; r[2].rows.forEach(function (a) { buckets[Core.agingBucket(daysSince(a.jo_date_closed))]++; });
        var el = $('#cqQStats'); if (!el) return;
        var agingLabel = 'Aging of queued (days since close)' + (r[2].total > r[2].rows.length ? ' (first ' + r[2].rows.length + ' of ' + r[2].total + ')' : '');
        el.innerHTML = '<div class="cq-stat"><span>Subcon closed this month</span><strong>' + r[0].total + '</strong></div><div class="cq-stat"><span>Subcon inspected</span><strong>' + r[1].total + '</strong></div><div class="cq-stat' + (r[2].total > 50 ? ' warn' : '') + '"><span>Queued (not assigned)</span><strong>' + r[2].total + '</strong></div><div class="cq-stat"><span>Assigned / in progress</span><strong>' + r[3].total + '</strong></div>' +
          '<div class="cq-stat' + (buckets['15-30'] + buckets['31+'] > 0 ? ' warn' : '') + '"><span>' + esc(agingLabel) + '</span><strong style="font-size:13px">0-7: ' + buckets['0-7'] + ' · 8-14: ' + buckets['8-14'] + ' · 15-30: ' + buckets['15-30'] + ' · 31+: ' + buckets['31+'] + '</strong></div>';
      });
    }
    function loadQueue() {
      var f = S.filter; $('#cqQTable').innerHTML = '<div class="cq-empty">Loading…</div>';
      api.listAudits({ status: f.status, contractor: f.contractor, kind: f.kind, from: f.from, to: f.to, q: f.q, page: f.page, pageSize: 50 }).then(function (r) {
        $('#q_page').textContent = 'Page ' + f.page + ' · ' + r.total + ' rows';
        if (!r.rows.length) { $('#cqQTable').innerHTML = '<div class="cq-empty">No audits match.</div>'; return; }
        $('#cqQTable').innerHTML = '<table><thead><tr>' + (canEdit ? '<th><input type="checkbox" id="q_all"></th>' : '') + '<th>Audit</th><th>Subscriber</th><th>Address</th><th>Contractor</th><th>JO closed</th><th>Aging</th><th>Status</th><th>Assigned</th></tr></thead><tbody>' + r.rows.map(function (a) {
          var d = daysSince(a.jo_date_closed);
          return '<tr>' + (canEdit ? '<td><input type="checkbox" data-sel="' + esc(a.id) + '"' + (S.sel[a.id] ? ' checked' : '') + '></td>' : '') + '<td><b>' + esc(a.id) + '</b><div class="cq-age">' + esc(a.jo_no || '') + (a.job_id ? ' · FieldOps' : '') + (a.unmapped ? ' · <span class="cq-pill fail">unmapped</span>' : '') + '</div></td><td><b>' + esc(a.subscriber || '') + '</b><div class="cq-age">' + esc(a.acct_no || '') + '</div></td><td>' + esc(a.address || '') + '<div class="cq-age">' + esc(a.barangay || '') + '</div></td><td>' + esc(a.contractor_name || '') + '<div class="cq-age">' + esc(a.kind || '') + '</div></td><td>' + esc(a.jo_date_closed || '—') + '</td><td class="cq-age ' + (d > 14 ? 'late' : '') + '">' + d + ' d</td><td>' + pill(a.status) + '</td><td>' + esc(a.assigned_to || '') + (a.scheduled_date ? '<div class="cq-age">' + esc(a.scheduled_date) + ' #' + (a.sequence || '') + '</div>' : '') + '</td></tr>';
        }).join('') + '</tbody></table>';
        rootEl.querySelectorAll('[data-sel]').forEach(function (cb) { cb.onchange = function () { S.sel[cb.dataset.sel] = cb.checked; syncButtons(); }; });
        var all = $('#q_all'); if (all) all.onchange = function () { rootEl.querySelectorAll('[data-sel]').forEach(function (cb) { cb.checked = all.checked; S.sel[cb.dataset.sel] = all.checked; }); syncButtons(); };
        syncButtons();
      });
    }
    function syncButtons() { var n = selIds().length; ['q_assign', 'q_pick', 'q_unassign'].forEach(function (id) { var b = $('#' + id); if (b) b.disabled = !n; }); }
    function assignDialog() {
      var ids = selIds(); if (!ids.length) return;
      modal('<h3 style="margin:0 0 10px">Assign ' + ids.length + ' audit(s)</h3><div class="cq-bar"><label>Inspector <select id="as_insp">' + inspectorOpts() + '</select></label><label>Date <input type="date" id="as_date" value="' + today() + '"></label><label>Start sequence # <input type="number" id="as_seq" value="1" min="1" style="width:70px"></label></div><div class="cq-age" style="margin-bottom:10px">Sequence = order of visits for that day. The inspector sees them in this order (push notification is wired at deploy).</div><div class="cq-bar" style="justify-content:flex-end"><button class="cq-btn ghost" id="as_cancel">Cancel</button><button class="cq-btn" id="as_ok">Assign</button></div>');
      $('#as_cancel').onclick = closeModal;
      $('#as_ok').onclick = function () { var insp = $('#as_insp').value, date = $('#as_date').value, seq = Number($('#as_seq').value || 1); if (!insp || !date) { toast('Pick an inspector and a date'); return; } closeModal(); act(api.assignAudits(ids, { inspector: insp, date: date, startSeq: seq, by: user.username }), 'assigned to ' + insp); };
    }
    function sampleDialog() {
      var pct = (S.cfg.settings || {}).inhouse_sample_pct || '10';
      modal('<h3 style="margin:0 0 10px">Random sample of in-house installs</h3><div class="cq-bar"><label>Closed from <input type="date" id="sm_from" value="' + addDays(today(), -7) + '"></label><label>to <input type="date" id="sm_to" value="' + today() + '"></label><label>Percent <input type="number" id="sm_pct" value="' + esc(pct) + '" min="1" max="100" style="width:70px"></label></div><div class="cq-age" style="margin-bottom:10px">Picks ceil(pool × %) random in-house pool rows closed in the range and moves them to Queued. Manual picks are still possible from the Pool filter.</div><div class="cq-bar" style="justify-content:flex-end"><button class="cq-btn ghost" id="sm_cancel">Cancel</button><button class="cq-btn" id="sm_ok">Sample</button></div>');
      $('#sm_cancel').onclick = closeModal;
      $('#sm_ok').onclick = function () { var o = { from: $('#sm_from').value, to: $('#sm_to').value, pct: Number($('#sm_pct').value), by: user.username }; closeModal(); act(api.sampleInhouse(o), 'sampled into the queue'); };
    }

    // ---------------- TODAY'S BOARD ----------------
    function renderBoard() {
      if (S.map) { try { S.map.remove(); } catch (e) {} }
      S.map = null;
      $('#cqBody').innerHTML = '<div class="cq-bar"><label>Date <input type="date" id="bd_date" value="' + S.boardDate + '"></label><button class="cq-btn ghost" id="bd_prev">‹</button><button class="cq-btn ghost" id="bd_next">›</button><span id="bd_sum" class="cq-age"></span></div><div class="cq-map" id="cqMap"></div><div class="cq-cols" id="cqCols"></div>';
      $('#bd_date').onchange = function () { S.boardDate = $('#bd_date').value; loadBoard(); };
      $('#bd_prev').onclick = function () { S.boardDate = addDays(S.boardDate, -1); $('#bd_date').value = S.boardDate; loadBoard(); };
      $('#bd_next').onclick = function () { S.boardDate = addDays(S.boardDate, 1); $('#bd_date').value = S.boardDate; loadBoard(); };
      loadBoard();
    }
    function loadBoard() {
      api.board(S.boardDate).then(function (rows) {
        var by = {}; rows.forEach(function (a) { (by[a.assigned_to] = by[a.assigned_to] || []).push(a); });
        var names = Object.keys(by).sort();
        $('#bd_sum').textContent = rows.length + ' assigned · ' + rows.filter(function (a) { return a.status === 'done'; }).length + ' done · ' + rows.filter(function (a) { return a.status === 'in_progress'; }).length + ' in progress';
        $('#cqCols').innerHTML = names.length ? names.map(function (n, i) {
          var list = by[n];
          return '<div class="cq-col"><h4><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:' + COLORS[i % COLORS.length] + ';margin-right:6px"></span>' + esc(n) + ' <span class="cq-age">' + list.filter(function (a) { return a.status === 'done'; }).length + '/' + list.length + ' done</span></h4>' +
            list.map(function (a) { return '<div class="cq-row"><b>#' + (a.sequence || '-') + ' ' + esc(a.subscriber || '') + '</b> ' + pill(a.status) + '<div class="cq-age">' + esc(a.address || '') + ' · ' + esc(a.contractor_name || '') + (a.started_at ? ' · started ' + fmtWhen(a.started_at) : '') + (a.inspected_at ? ' · done ' + fmtWhen(a.inspected_at) : '') + '</div>' +
              (canEdit && a.status === 'assigned' ? '<div style="margin-top:4px"><select data-re="' + esc(a.id) + '"><option value="">Reassign to…</option>' + inspectorOpts() + '</select> <input type="number" min="1" value="' + (a.sequence || 1) + '" data-seq="' + esc(a.id) + '" style="width:56px" title="Visit order"> <button class="cq-btn ghost" data-un="' + esc(a.id) + '" style="padding:3px 8px">Unassign</button></div>' : '') + (a.status === 'done' ? '<div style="margin-top:4px"><button class="cq-btn ghost" data-view="' + esc(a.id) + '" style="padding:3px 8px">View result</button></div>' : '') + '</div>'; }).join('') + '</div>';
        }).join('') : '<div class="cq-empty">Nothing assigned for ' + esc(S.boardDate) + '.</div>';
        rootEl.querySelectorAll('[data-re]').forEach(function (s) { s.onchange = function () { if (!s.value) return; var a = rows.filter(function (x) { return x.id === s.dataset.re; })[0]; api.assignAudits([a.id], { inspector: s.value, date: S.boardDate, startSeq: a.sequence || 1, by: user.username }).then(function () { toast('Reassigned'); loadBoard(); }); }; });
        rootEl.querySelectorAll('[data-un]').forEach(function (b) { b.onclick = function () { api.unassignAudits([b.dataset.un], { by: user.username }).then(function () { toast('Unassigned'); loadBoard(); }); }; });
        rootEl.querySelectorAll('[data-seq]').forEach(function (input) { input.onchange = function () { var a = rows.filter(function (x) { return x.id === input.dataset.seq; })[0]; if (!a) return; api.assignAudits([a.id], { inspector: a.assigned_to, date: S.boardDate, startSeq: Number(input.value) || 1, by: user.username }).then(function () { toast('Order updated'); loadBoard(); }); }; });
        rootEl.querySelectorAll('[data-view]').forEach(function (b) { b.onclick = function () { openDetail(b.dataset.view); }; });
        drawMap(rows, names);
      });
    }
    function drawMap(rows, names) {
      var el = $('#cqMap'); if (!el || !L) { if (el) el.innerHTML = '<div class="cq-empty">Map unavailable</div>'; return; }
      if (!S.map) { S.map = L.map(el, { zoomControl: true, attributionControl: false }).setView([14.68, 121.06], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19 }).addTo(S.map); }
      if (S.layer) S.map.removeLayer(S.layer); S.layer = L.layerGroup().addTo(S.map);
      var pts = [];
      rows.forEach(function (a) {
        var ll = null; if (a.lat != null && a.lng != null) ll = [a.lat, a.lng]; else if (a.sheet_latlong) { var m = /(-?\d+\.\d+)[,\s]+(-?\d+\.\d+)/.exec(a.sheet_latlong); if (m) ll = [parseFloat(m[1]), parseFloat(m[2])]; }
        if (!ll) return; pts.push(ll);
        L.circleMarker(ll, { radius: 8, weight: 2, color: COLORS[names.indexOf(a.assigned_to) % COLORS.length], fillColor: a.status === 'done' ? '#fff' : COLORS[names.indexOf(a.assigned_to) % COLORS.length], fillOpacity: .9 }).addTo(S.layer).bindPopup('<b>#' + (a.sequence || '') + ' ' + esc(a.subscriber || '') + '</b><br>' + esc(a.assigned_to) + ' · ' + esc(a.status));
      });
      if (pts.length) S.map.fitBounds(pts, { padding: [20, 20] });
      setTimeout(function () { S.map.invalidateSize(); }, 150);
    }

    // ---------------- stubs replaced in Tasks 10–11 ----------------
    // ---------------- RESULTS ----------------
    function renderResults() {
      var r = S.results;
      $('#cqBody').innerHTML = '<div class="cq-bar"><label>QA date from <input type="date" id="rf_from" value="' + esc(r.qfrom || addDays(today(), -6)) + '"></label><label>to <input type="date" id="rf_to" value="' + esc(r.qto || today()) + '"></label><select id="rf_contractor">' + contractorOpts() + '</select><select id="rf_insp"><option value="">All inspectors</option>' + inspectorOpts() + '</select><select id="rf_assess"><option value="">Any assessment</option>' + Core.ASSESS.map(function (a) { return '<option>' + a + '</option>'; }).join('') + '</select><input id="rf_q" placeholder="Search"><button class="cq-btn ghost" id="rf_go">Filter</button></div><div id="cqRTable"></div><div class="cq-bar" style="justify-content:flex-end"><button class="cq-btn ghost" id="r_prev">‹ Prev</button><span id="r_page"></span><button class="cq-btn ghost" id="r_next">Next ›</button></div>';
      if (r.contractor) $('#rf_contractor').value = r.contractor; if (r.inspector) $('#rf_insp').value = r.inspector; if (r.assessment) $('#rf_assess').value = r.assessment;
      $('#rf_go').onclick = function () { S.results = { qfrom: $('#rf_from').value, qto: $('#rf_to').value, contractor: $('#rf_contractor').value, inspector: $('#rf_insp').value, assessment: $('#rf_assess').value, q: $('#rf_q').value, page: 1 }; loadResults(); };
      $('#r_prev').onclick = function () { if (S.results.page > 1) { S.results.page--; loadResults(); } };
      $('#r_next').onclick = function () { S.results.page++; loadResults(); };
      if (!r.qfrom) { S.results.qfrom = addDays(today(), -6); S.results.qto = today(); }
      loadResults();
    }
    function loadResults() {
      var r = S.results; $('#cqRTable').innerHTML = '<div class="cq-empty">Loading…</div>';
      api.listAudits({ status: ['done'], qfrom: r.qfrom, qto: r.qto, contractor: r.contractor, inspector: r.inspector, assessment: r.assessment, q: r.q, page: r.page, pageSize: 50 }).then(function (res) {
        $('#r_page').textContent = 'Page ' + r.page + ' · ' + res.total + ' rows';
        if (!res.rows.length) { $('#cqRTable').innerHTML = '<div class="cq-empty">No results in this range.</div>'; return; }
        $('#cqRTable').innerHTML = '<table><thead><tr><th>Audit</th><th>Subscriber</th><th>Contractor</th><th>Inspector</th><th>QA date</th><th>Visit</th><th>Assessment</th><th>Violations</th><th>Penalty</th><th></th></tr></thead><tbody>' + res.rows.map(function (a) {
          return '<tr><td><b>' + esc(a.id) + '</b><div class="cq-age">' + esc(a.jo_no || '') + (a.source === 'sheet_legacy' ? ' · legacy' : '') + (a.reopened_count ? ' · reopened ×' + a.reopened_count : '') + '</div></td><td><b>' + esc(a.subscriber || '') + '</b><div class="cq-age">' + esc(a.address || '') + '</div></td><td>' + esc(a.contractor_name || '') + '</td><td>' + esc(a.inspector || '') + '</td><td>' + fmtWhen(a.inspected_at) + '</td><td>' + esc(a.visit_status || '') + '</td><td>' + (a.assessment ? '<span class="cq-pill ' + (a.assessment === 'GOOD' ? 'done' : 'fail') + '">' + esc(a.assessment) + '</span>' : '') + '</td><td>' + a.total_violations + '</td><td>' + peso(a.total_penalty) + '</td><td><button class="cq-btn ghost" data-view="' + esc(a.id) + '" style="padding:3px 8px">Open</button></td></tr>';
        }).join('') + '</tbody></table>';
        rootEl.querySelectorAll('[data-view]').forEach(function (b) { b.onclick = function () { openDetail(b.dataset.view); }; });
      });
    }
    function openDetail(id) {
      modal('<div class="cq-empty">Loading ' + esc(id) + '…</div>');
      api.getAudit(id).then(function (r) {
        var a = r.audit;
        var byItem = {}; r.items.forEach(function (i) { byItem[i.item_id] = i; });
        var html = '<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:10px"><div><h3 style="margin:0">' + esc(a.id) + ' · ' + esc(a.subscriber || '') + '</h3><div class="cq-age">' + esc(a.contractor_name || '') + ' · ' + pill(a.status) + ' · ' + esc(a.visit_status || '') + (a.assessment ? ' · <b>' + esc(a.assessment) + '</b>' : '') + '</div></div><div style="display:flex;gap:6px"><button class="cq-btn ghost" id="dt_print">🖨 Print / PDF</button>' + (canEdit && a.status === 'done' && a.assigned_to ? '<button class="cq-btn warn" id="dt_reopen">Reopen</button>' : '') + '<button class="cq-btn ghost" id="dt_close">Close</button></div></div>' +
          '<div class="cq-sec">Header</div><div class="cq-grid"><div><b>Inspection date</b>' + fmtWhen(a.inspected_at) + '</div><div><b>Inspector</b>' + esc(a.inspector || '—') + '</div><div><b>Contractor\'s rep</b>' + esc(a.contractor_rep || '—') + '</div><div><b>Installer/s</b>' + esc(a.installers_text || '—') + '</div><div><b>Account no.</b>' + esc(a.acct_no || '—') + '</div><div><b>JO no.</b>' + esc(a.jo_no || '—') + '</div><div><b>Address</b>' + esc(a.address || '') + ' ' + esc(a.barangay || '') + '</div><div><b>NAP / Port / S/N</b>' + esc(a.nap_code || '—') + ' / ' + esc(a.port_no || '—') + ' / ' + esc(a.serial_no || '—') + '</div><div><b>GPS</b>' + (a.lat != null ? '<a href="https://www.google.com/maps/search/?api=1&query=' + a.lat + ',' + a.lng + '" target="_blank" rel="noopener">' + a.lat.toFixed(5) + ', ' + a.lng.toFixed(5) + '</a>' : '—') + '</div><div><b>Wire</b>' + esc(a.wire || '—') + '</div><div><b>QA / GC</b>' + esc(a.qa_gc || '—') + '</div><div><b>Found business</b>' + esc(a.found_business ? a.found_business.replace('_', ' ') + ' · old ' + (a.old_plan || '—') + ' · new ' + (a.new_plan || '—') : '—') + '</div></div>' +
          (r.items.length ? '<div class="cq-sec">Checklist</div><table><thead><tr><th>Item</th><th>Result</th><th>Remark</th><th>Photos</th></tr></thead><tbody>' + S.cfg.checklist.map(function (c) { var i = byItem[c.id] || {}; return '<tr><td>' + esc(c.label) + '<div class="cq-age">' + esc(c.section) + '</div></td><td>' + (i.result ? '<span class="cq-pill ' + (i.result === 'fail' ? 'fail' : i.result === 'pass' ? 'done' : '') + '">' + i.result.toUpperCase() + '</span>' : '—') + '</td><td>' + esc(i.remark || '') + '</td><td><div class="cq-thumbs" data-ph="' + c.id + '"></div></td></tr>'; }).join('') + '</tbody></table>' : '') +
          (r.violations.length ? '<div class="cq-sec">Violations</div><table><thead><tr><th>Code</th><th>Category</th><th>Description</th><th>Class</th><th>Severity</th><th>No. of offense</th><th>Penalty</th></tr></thead><tbody>' + r.violations.map(function (v) { return '<tr><td><b>' + esc(v.code) + '</b></td><td>' + esc(v.category || '') + '</td><td>' + esc(v.description || '') + (v.remark ? '<div class="cq-age">' + esc(v.remark) + '</div>' : '') + '</td><td>' + esc(v.class || '') + '</td><td>' + esc(v.severity || '') + '</td><td>' + (v.offense_no || '—') + '</td><td>' + (v.penalty_amount != null ? peso(v.penalty_amount) : '—') + '</td></tr>'; }).join('') + '<tr><td colspan="6"><b>TOTAL VIOLATION FOUND: ' + a.total_violations + '</b></td><td><b>' + peso(a.total_penalty) + '</b></td></tr></tbody></table>' : '') +
          '<div class="cq-sec">Remarks</div><div>' + esc(a.remarks || '—') + '</div><div class="cq-sec">Other photos</div><div class="cq-thumbs" data-ph="x"></div><div class="cq-sec">Signatures</div><div class="cq-thumbs"><div><div class="cq-age">Subscriber: ' + esc(a.subscriber_signed_name || '—') + '</div><img data-sig="' + esc(a.subscriber_signature_path || '') + '" alt="" style="background:#fff"></div><div><div class="cq-age">Inspector: ' + esc(a.inspector || '') + '</div><img data-sig="' + esc(a.inspector_signature_path || '') + '" alt="" style="background:#fff"></div></div>' +
          '<div class="cq-sec">Log</div><table><tbody>' + r.log.map(function (l) { return '<tr><td class="cq-age" style="white-space:nowrap">' + fmtWhen(l.at) + '</td><td><b>' + esc(l.action) + '</b> · ' + esc(l.by) + '</td><td class="cq-age">' + esc(l.detail ? JSON.stringify(l.detail) : '') + '</td></tr>'; }).join('') + '</tbody></table>';
        modal(html);
        $('#dt_close').onclick = closeModal;
        var urls = {};
        var fill = function (path, sel) { if (!path) return; api.photoUrl(path).then(function (u) { urls[path] = u; rootEl.querySelectorAll(sel).forEach(function (img) { img.src = u; }); }); };
        r.photos.forEach(function (p) { var box = rootEl.querySelector('[data-ph="' + (p.item_id || 'x') + '"]'); if (!box) return; var img = document.createElement('img'); img.alt = p.label || ''; img.title = p.label || ''; box.appendChild(img); api.photoUrl(p.path).then(function (u) { urls[p.path] = u; img.src = u; img.onclick = function () { window.open(u, '_blank', 'noopener'); }; }); });
        fill(a.subscriber_signature_path, '[data-sig="' + a.subscriber_signature_path + '"]'); fill(a.inspector_signature_path, '[data-sig="' + a.inspector_signature_path + '"]');
        $('#dt_print').onclick = function () { printForm(r, urls); };
        var re = $('#dt_reopen'); if (re) re.onclick = function () { var why = prompt('Reason for reopening ' + a.id + ' (the inspector will be able to edit and resubmit):'); if (why == null) return; api.reopenAudit(a.id, { by: user.username, reason: why }).then(function () { toast(a.id + ' reopened'); closeModal(); render(); }).catch(function (e) { toast('Failed: ' + e.message); }); };
      }).catch(function (e) { modal('<div class="cq-empty">Could not load: ' + esc(e.message) + '</div><button class="cq-btn ghost" onclick="this.parentNode.parentNode.innerHTML=\'\'">Close</button>'); });
    }
    // Paper-form replica (QUALITY ASSURANCE INSPECTION FORM) → new window → print/PDF.
    function printForm(r, urls) {
      var a = r.audit, byItem = {}; r.items.forEach(function (i) { byItem[i.item_id] = i; });
      var sec = function (name) { return '<tr class="sec"><td colspan="3">' + esc(name) + '</td></tr>'; };
      var items = [sec('Outside Segment of Installation')].concat(S.cfg.checklist.filter(function (c) { return c.section === 'OUTSIDE'; }).map(function (c) { var i = byItem[c.id] || {}; return '<tr><td>• ' + esc(c.label) + '</td><td class="c">' + (i.result === 'pass' ? '✔' : i.result === 'na' ? 'N/A' : '') + '</td><td class="c">' + (i.result === 'fail' ? '✘ ' + esc(i.remark || '') : '') + '</td></tr>'; }))
        .concat([sec('Client Premise Segment of Installation')]).concat(S.cfg.checklist.filter(function (c) { return c.section === 'PREMISE'; }).map(function (c) { var i = byItem[c.id] || {}; return '<tr><td>• ' + esc(c.label) + '</td><td class="c">' + (i.result === 'pass' ? '✔' : i.result === 'na' ? 'N/A' : '') + '</td><td class="c">' + (i.result === 'fail' ? '✘ ' + esc(i.remark || '') : '') + '</td></tr>'; })).join('');
      var viol = r.violations.map(function (v) { return '<tr><td>' + esc(v.code) + '</td><td>' + esc(v.category || '') + '</td><td>' + esc(v.description || '') + '</td><td>' + esc(v.class || '') + '</td><td>' + esc(v.severity || '') + '</td><td>' + (v.offense_no || '') + '</td><td>' + (v.penalty_amount != null ? peso(v.penalty_amount) : '') + '</td></tr>'; }).join('') + Array(Math.max(0, 5 - r.violations.length) + 1).join('<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>');
      var photos = r.photos.map(function (p) { return urls[p.path] ? '<div class="ph"><img src="' + esc(urls[p.path]) + '"><div>' + esc(p.label || '') + '</div></div>' : ''; }).join('');
      var html = '<!doctype html><html><head><meta charset="utf-8"><title>' + esc(a.id) + ' QA Inspection Form</title><style>body{font:12px Arial,sans-serif;color:#000;margin:18px}h1{background:#1d9e3f;color:#fff;font-size:14px;text-align:center;padding:5px;margin:0 0 6px}table{width:100%;border-collapse:collapse;margin-bottom:8px}td,th{border:1px solid #000;padding:4px 6px;font-size:11px;vertical-align:top}td.k{width:170px;background:#f3f3f3}tr.sec td{background:#c9e8cf;font-weight:bold}th{background:#1d9e3f;color:#fff}td.c{width:120px;text-align:center}.cert{margin:10px 0;font-size:11px}.sig{display:flex;justify-content:space-between;margin-top:18px}.sig div{width:45%}.sig img{height:60px;display:block}.ph{display:inline-block;width:23%;margin:1%;font-size:9px;text-align:center}.ph img{width:100%;height:120px;object-fit:cover;border:1px solid #999}@media print{.no{display:none}}</style></head><body>' +
        '<div class="no" style="text-align:right;margin-bottom:6px"><button onclick="window.print()">Print / Save as PDF</button></div><h1>QUALITY ASSURANCE INSPECTION FORM</h1>' +
        '<table><tr><td class="k">Inspection/Ticket no.</td><td>' + esc(a.id) + '</td><td class="k">Client\'s Name:</td><td>' + esc(a.subscriber || '') + '</td></tr><tr><td class="k">Inspection Date:</td><td>' + fmtWhen(a.inspected_at) + '</td><td class="k">Client\'s Account No.:</td><td>' + esc(a.acct_no || '') + '</td></tr><tr><td class="k">Inspector\'s Name:</td><td>' + esc(a.inspector || '') + '</td><td class="k">Address:</td><td>' + esc((a.address || '') + ' ' + (a.barangay || '')) + '</td></tr><tr><td class="k">Contractor\'s Representative:</td><td>' + esc(a.contractor_rep || '') + '</td><td class="k">JO / NAP / Port</td><td>' + esc((a.jo_no || '') + ' / ' + (a.nap_code || '') + ' / ' + (a.port_no || '')) + '</td></tr><tr><td class="k">Installer/s:</td><td>' + esc(a.installers_text || '') + '</td><td class="k">Visit / Wire / QA-GC</td><td>' + esc((a.visit_status || '') + ' / ' + (a.wire || '') + ' / ' + (a.qa_gc || '')) + '</td></tr><tr><td class="k">Contractor/ Dept:</td><td>' + esc(a.contractor_name || '') + '</td><td class="k">Assessment</td><td><b>' + esc(a.assessment || '') + '</b></td></tr></table>' +
        '<table><tr><th style="text-align:left">DESCRIPTION</th><th>PASSED</th><th>FAILED</th></tr>' + items + '</table>' +
        '<table><tr><th>CODE</th><th>CATEGORY</th><th>DESCRIPTION</th><th>CLASS</th><th>SEVERITY</th><th>NO. OF OFFENSE</th><th>PENALTY</th></tr>' + viol + '<tr><td colspan="6"><b>TOTAL VIOLATION FOUND:</b> ' + a.total_violations + '</td><td></td></tr><tr><td colspan="6"><b>TOTAL PENALTY:</b></td><td><b>' + peso(a.total_penalty) + '</b></td></tr></table>' +
        '<table><tr class="sec"><td colspan="4">FOUND BUSINESS</td></tr><tr><td class="c">' + (a.found_business === 'willing' ? '☑' : '☐') + '</td><td><b>WILLING TO UPGRADE</b></td><td class="k">OLD PLAN:</td><td>' + esc(a.old_plan || '') + '</td></tr><tr><td class="c">' + (a.found_business === 'not_willing' ? '☑' : '☐') + '</td><td><b>NOT WILLING TO UPGRADE (Subject for termination)</b></td><td class="k">NEW PLAN:</td><td>' + esc(a.new_plan || '') + '</td></tr></table>' +
        '<div class="cert">I, <u>&nbsp;' + esc(a.subscriber_signed_name || '') + '&nbsp;</u> the client, understands that there is a non-compliance regarding my subscription and that I need to change and/or upgrade from residential plan to business plan.</div><div class="cert">I, the inspector, hereby certify that the inspection has been performed in a fair, professional, and honest way, and that I have not asked, nor received any favour, compensation or gifts from anyone.</div>' +
        '<div class="sig"><div><b>Subscriber\'s Name:</b> ' + esc(a.subscriber_signed_name || '') + '<br><b>Signature:</b>' + (urls[a.subscriber_signature_path] ? '<img src="' + esc(urls[a.subscriber_signature_path]) + '">' : '<br><br>') + '</div><div><b>Name of Inspector:</b> ' + esc(a.inspector || '') + '<br><b>Signature:</b>' + (urls[a.inspector_signature_path] ? '<img src="' + esc(urls[a.inspector_signature_path]) + '">' : '<br><br>') + '</div></div>' +
        (a.remarks ? '<div class="cert"><b>Remarks:</b> ' + esc(a.remarks) + '</div>' : '') + (photos ? '<div style="page-break-before:always"><h1>PHOTOS · ' + esc(a.id) + '</h1>' + photos + '</div>' : '') + '</body></html>';
      var w = window.open('', '_blank'); if (!w) { toast('Pop-up blocked — allow pop-ups to print'); return; } w.document.write(html); w.document.close();
    }
    // ---------------- REPORTS ----------------
    function dl(name, text, mime) { var b = new Blob([text], { type: mime || 'text/csv' }); var a = document.createElement('a'); a.href = URL.createObjectURL(b); a.download = name; a.click(); setTimeout(function () { URL.revokeObjectURL(a.href); }, 5000); }
    function exportRows(name, rows) {
      if (!rows.length) { toast('Nothing to export'); return; }
      var cols = Object.keys(rows[0]);
      var toXlsx = deps.ensureXLSX ? deps.ensureXLSX().then(function () { var ws = root.XLSX.utils.json_to_sheet(rows); var wb = root.XLSX.utils.book_new(); root.XLSX.utils.book_append_sheet(wb, ws, 'QA'); root.XLSX.writeFile(wb, name + '.xlsx'); }) : Promise.reject();
      toXlsx.catch(function () { dl(name + '.csv', cols.join(',') + '\n' + rows.map(function (r) { return cols.map(function (c) { return '"' + String(r[c] == null ? '' : r[c]).replace(/"/g, '""') + '"'; }).join(','); }).join('\n')); });
    }
    function renderReports() {
      var rp = S.report;
      $('#cqBody').innerHTML = '<div class="cq-bar"><b>Daily</b><label>Date <input type="date" id="rp_day" value="' + today() + '"></label><button class="cq-btn ghost" id="rp_dayShow">Show</button><button class="cq-btn ghost" id="rp_dayX">Export day</button><button class="cq-btn ghost" id="rp_dayPrint">Print all forms</button></div><div id="rp_dayT"></div>' +
        '<div class="cq-bar" style="margin-top:16px"><b>Weekly review</b><label>From <input type="date" id="rp_from" value="' + esc(rp.from) + '"></label><label>to <input type="date" id="rp_to" value="' + esc(rp.to) + '"></label><button class="cq-btn ghost" id="rp_prevW">‹ week</button><button class="cq-btn ghost" id="rp_nextW">week ›</button><button class="cq-btn" id="rp_run">Run</button><button class="cq-btn ghost" id="rp_x">Export (SUMMARY PER CON)</button></div><div id="rp_week"></div>';
      $('#rp_dayShow').onclick = loadDay; $('#rp_dayX').onclick = function () { dayRows().then(function (rows) { exportRows('QA-daily-' + $('#rp_day').value, rows); }); };
      $('#rp_dayPrint').onclick = function () { api.listAudits({ status: ['done'], qfrom: $('#rp_day').value, qto: $('#rp_day').value, pageSize: 1000 }).then(function (r) { if (!r.rows.length) { toast('No inspections that day'); return; } if (!confirm('Open ' + r.rows.length + ' print window(s)?')) return; r.rows.forEach(function (a) { api.getAudit(a.id).then(function (b) { var urls = {}; Promise.all(b.photos.map(function (p) { return api.photoUrl(p.path).then(function (u) { urls[p.path] = u; }); }).concat([a.subscriber_signature_path, a.inspector_signature_path].filter(Boolean).map(function (p) { return api.photoUrl(p).then(function (u) { urls[p] = u; }); }))).then(function () { printForm(b, urls); }); }); }); }); };
      $('#rp_prevW').onclick = function () { S.report = { from: addDays(S.report.from, -7), to: addDays(S.report.to, -7) }; renderReports(); };
      $('#rp_nextW').onclick = function () { S.report = { from: addDays(S.report.from, 7), to: addDays(S.report.to, 7) }; renderReports(); };
      $('#rp_run').onclick = function () { S.report = { from: $('#rp_from').value, to: $('#rp_to').value }; loadWeek(); };
      $('#rp_x').onclick = function () { api.weeklyReport(S.report.from, S.report.to).then(function (w) { exportRows('QA-weekly-' + S.report.from + '_' + S.report.to, w.contractors.map(function (c) { return { COMP: c.contractor, INSPECTED: c.inspected, GOOD: c.GOOD, 'FOR RECTIFY': c['FOR RECTIFY'], 'FOR PENALTY': c['FOR PENALTY'], CLAWBACK: c.CLAWBACK, NPA: c.npa, PENALTY: c.penalty, CLOSED: c.closed, 'COVERAGE %': c.closed ? Math.round(c.inspected * 100 / c.closed) : '' }; })); }); };
      loadDay(); loadWeek();
    }
    function dayRows() { var d = $('#rp_day').value; return api.listAudits({ status: ['done'], qfrom: d, qto: d, pageSize: 1000 }).then(function (r) { return r.rows.map(function (a) { return { AUDIT: a.id, DATE_QA: a.inspected_at ? a.inspected_at.slice(0, 10) : '', INSPECTOR: a.inspector, COMP: a.contractor_name, JONO: a.jo_no, ACCTNO: a.acct_no, SUBSCRIBER: a.subscriber, ADDRESS: a.address, BARANGAY: a.barangay, NAP: a.nap_code, PORT: a.port_no, VISITED: a.visit_status, WIRE: a.wire, 'QA / GC': a.qa_gc, ASSESSMENT: a.assessment, VIOLATIONS: a.total_violations, PENALTY: a.total_penalty, REMARKS: a.remarks, LATLONG: a.lat != null ? a.lat + ', ' + a.lng : a.sheet_latlong, 'CONTRACTOR REP': a.contractor_rep, INSTALLERS: a.installers_text, 'FOUND BUSINESS': a.found_business, 'OLD PLAN': a.old_plan, 'NEW PLAN': a.new_plan }; }); }); }
    function loadDay() { $('#rp_dayT').innerHTML = '<div class="cq-empty">Loading…</div>'; dayRows().then(function (rows) { $('#rp_dayT').innerHTML = rows.length ? '<table><thead><tr>' + ['AUDIT', 'INSPECTOR', 'COMP', 'SUBSCRIBER', 'BARANGAY', 'VISITED', 'ASSESSMENT', 'VIOLATIONS', 'PENALTY'].map(function (c) { return '<th>' + c + '</th>'; }).join('') + '</tr></thead><tbody>' + rows.map(function (r) { return '<tr><td><a href="#" data-view="' + esc(r.AUDIT) + '">' + esc(r.AUDIT) + '</a></td><td>' + esc(r.INSPECTOR) + '</td><td>' + esc(r.COMP) + '</td><td>' + esc(r.SUBSCRIBER) + '</td><td>' + esc(r.BARANGAY) + '</td><td>' + esc(r.VISITED) + '</td><td>' + esc(r.ASSESSMENT) + '</td><td>' + r.VIOLATIONS + '</td><td>' + peso(r.PENALTY) + '</td></tr>'; }).join('') + '</tbody></table>' : '<div class="cq-empty">No inspections on that day.</div>'; rootEl.querySelectorAll('#rp_dayT [data-view]').forEach(function (a) { a.onclick = function (e) { e.preventDefault(); openDetail(a.dataset.view); }; }); }); }
    function loadWeek() {
      $('#rp_week').innerHTML = '<div class="cq-empty">Loading…</div>';
      api.weeklyReport(S.report.from, S.report.to).then(function (w) {
        var tbl = function (title, heads, rows) { return '<div class="cq-sec">' + title + '</div>' + (rows.length ? '<table><thead><tr>' + heads.map(function (x) { return '<th>' + x + '</th>'; }).join('') + '</tr></thead><tbody>' + rows.join('') + '</tbody></table>' : '<div class="cq-empty">No data</div>'); };
        $('#rp_week').innerHTML = tbl('Per contractor (' + esc(S.report.from) + ' → ' + esc(S.report.to) + ')', ['Contractor', 'Closed', 'Inspected', 'Coverage', 'GOOD', 'FOR RECTIFY', 'FOR PENALTY', 'CLAWBACK', 'NPA/other', 'Penalty'], w.contractors.map(function (c) { var pct = c.closed ? Math.round(c.inspected * 100 / c.closed) : null; return '<tr><td><b>' + esc(c.contractor) + '</b></td><td>' + c.closed + '</td><td>' + c.inspected + '</td><td>' + (pct == null ? '—' : '<span class="cq-pill ' + (pct >= 100 ? 'done' : pct >= 50 ? 'queued' : 'fail') + '">' + pct + '%</span>') + '</td><td>' + c.GOOD + '</td><td>' + c['FOR RECTIFY'] + '</td><td>' + c['FOR PENALTY'] + '</td><td>' + c.CLAWBACK + '</td><td>' + c.npa + '</td><td>' + peso(c.penalty) + '</td></tr>'; })) +
          tbl('Checklist pass rate', ['Item', 'Pass', 'Fail', 'N/A', 'Pass rate'], w.items.map(function (i) { return '<tr><td>' + esc(i.label) + '</td><td>' + i.pass + '</td><td>' + i.fail + '</td><td>' + i.na + '</td><td>' + (i.pass_rate == null ? '—' : '<span class="cq-pill ' + (i.pass_rate >= 90 ? 'done' : i.pass_rate >= 70 ? 'queued' : 'fail') + '">' + i.pass_rate + '%</span>') + '</td></tr>'; })) +
          tbl('Top violations', ['Code', 'Category', 'Count'], w.codes.map(function (c) { return '<tr><td><b>' + esc(c.code) + '</b></td><td>' + esc(c.category || '') + '</td><td>' + c.count + '</td></tr>'; })) +
          tbl('Inspectors', ['Inspector', 'Inspections', 'NPA/other'], w.inspectors.map(function (i) { return '<tr><td>' + esc(i.inspector) + '</td><td>' + i.inspections + '</td><td>' + i.npa + '</td></tr>'; }));
      }).catch(function (e) { $('#rp_week').innerHTML = '<div class="cq-empty">' + esc(e.message) + '</div>'; });
    }

    // ---------------- SETTINGS ----------------
    function renderSettings() {
      var c = S.cfg, s = c.settings || {};
      var lastSync = S.sync && S.sync.last_sync_at ? fmtWhen(S.sync.last_sync_at) + ' · ' + S.sync.last_sync_rows + ' rows' : 'never';
      $('#cqBody').innerHTML = '<div class="cq-sec">Sheet sync</div><div class="cq-stats"><div class="cq-stat"><span>Last sync</span><strong style="font-size:13px">' + esc(lastSync) + '</strong></div><div class="cq-stat' + (S.sync && S.sync.unmapped.length ? ' warn' : '') + '"><span>Unmapped contractor names</span><strong style="font-size:13px">' + esc((S.sync && S.sync.unmapped.join(', ')) || 'none') + '</strong></div></div>' +
        (canEdit ? '<div class="cq-bar"><label>CSV fallback (same columns as the sheet: COMP, JODATECLOSED, ACCTNO, JONO, …) <input type="file" id="st_csv" accept=".csv"></label><button class="cq-btn ghost" id="st_csvGo">Import CSV</button></div>' : '') +
        '<div class="cq-sec">General</div><div class="cq-bar"><label>In-house sample % <input type="number" id="st_pct" value="' + esc(s.inhouse_sample_pct || '10') + '" min="0" max="100" style="width:70px"' + (canEdit ? '' : ' disabled') + '></label><label>Initial cutoff (rows closed before this are never auto-queued) <input type="date" id="st_cut" value="' + esc(s.initial_cutoff || '') + '"' + (canEdit ? '' : ' disabled') + '></label>' + (canEdit ? '<button class="cq-btn" id="st_save">Save</button>' : '') + '</div>' +
        '<div class="cq-sec">Contractor mapping</div><table><thead><tr><th>Sheet name (COMP)</th><th>Display name</th><th>Kind</th><th>Coverage</th><th>FieldOps org id</th><th>Active</th></tr></thead><tbody>' + c.contractors.map(function (x) { return '<tr data-ct="' + esc(x.sheet_name) + '"><td><b>' + esc(x.sheet_name) + '</b></td><td><input data-f="display_name" value="' + esc(x.display_name) + '"></td><td><select data-f="kind"><option' + (x.kind === 'subcon' ? ' selected' : '') + '>subcon</option><option' + (x.kind === 'inhouse' ? ' selected' : '') + '>inhouse</option></select></td><td><select data-f="coverage"><option' + (x.coverage === 'all' ? ' selected' : '') + '>all</option><option' + (x.coverage === 'sample' ? ' selected' : '') + '>sample</option></select></td><td><input data-f="org_id" value="' + esc(x.org_id || '') + '" placeholder="uuid from Subcontractors page" style="width:260px"></td><td><input type="checkbox" data-f="active"' + (x.active ? ' checked' : '') + '></td></tr>'; }).join('') + (canEdit ? '<tr><td><input id="ct_new" placeholder="NEW SHEET NAME"></td><td colspan="5"><button class="cq-btn ghost" id="ct_add">Add</button></td></tr>' : '') + '</tbody></table>' +
        '<div class="cq-sec">Checklist items</div><table><thead><tr><th>Section</th><th>Label</th><th>Order</th><th>Suggested code</th><th>Active</th></tr></thead><tbody>' + c.checklist.map(function (x) { return '<tr data-ci="' + x.id + '"><td><select data-f="section"><option' + (x.section === 'OUTSIDE' ? ' selected' : '') + '>OUTSIDE</option><option' + (x.section === 'PREMISE' ? ' selected' : '') + '>PREMISE</option></select></td><td><input data-f="label" value="' + esc(x.label) + '" style="width:320px"></td><td><input data-f="sort_order" type="number" value="' + x.sort_order + '" style="width:60px"></td><td><input data-f="suggested_code" value="' + esc(x.suggested_code || '') + '" style="width:90px"></td><td><input type="checkbox" data-f="active"' + (x.active ? ' checked' : '') + '></td></tr>'; }).join('') + (canEdit ? '<tr><td><select id="ci_sec"><option>OUTSIDE</option><option>PREMISE</option></select></td><td><input id="ci_label" placeholder="New item label" style="width:320px"></td><td colspan="3"><button class="cq-btn ghost" id="ci_add">Add</button></td></tr>' : '') + '</tbody></table>' +
        '<div class="cq-sec">Violation catalog (' + c.codes.length + ')</div><div class="cq-bar"><input id="vc_q" placeholder="Filter codes"></div><div id="vc_table"></div>';
      var renderCodes = function () { var q = ($('#vc_q').value || '').toUpperCase(); var rows = c.codes.filter(function (x) { return !q || (x.code + ' ' + x.category + ' ' + x.description).toUpperCase().indexOf(q) >= 0; }).slice(0, 60); $('#vc_table').innerHTML = '<table><thead><tr><th>Code</th><th>Category</th><th>Severity</th><th>L1</th><th>L2</th><th>L3</th><th>Penalty text</th><th>Active</th></tr></thead><tbody>' + rows.map(function (x) { return '<tr data-vc="' + esc(x.code) + '"><td><b>' + esc(x.code) + '</b></td><td><input data-f="category" value="' + esc(x.category) + '" style="width:220px"></td><td><select data-f="severity"><option' + (x.severity === 'MINOR' ? ' selected' : '') + '>MINOR</option><option' + (x.severity === 'MAJOR' ? ' selected' : '') + '>MAJOR</option><option' + (x.severity === 'CRITICAL' ? ' selected' : '') + '>CRITICAL</option></select></td><td><input data-f="penalty_l1" type="number" value="' + (x.penalty_l1 == null ? '' : x.penalty_l1) + '" style="width:70px"></td><td><input data-f="penalty_l2" type="number" value="' + (x.penalty_l2 == null ? '' : x.penalty_l2) + '" style="width:70px"></td><td><input data-f="penalty_l3" type="number" value="' + (x.penalty_l3 == null ? '' : x.penalty_l3) + '" style="width:70px"></td><td class="cq-age">' + esc(String(x.penalty_text || '').slice(0, 80)) + '</td><td><input type="checkbox" data-f="active"' + (x.active !== false ? ' checked' : '') + '></td></tr>'; }).join('') + '</tbody></table>' + (c.codes.length > rows.length ? '<div class="cq-age">Showing ' + rows.length + ' of ' + c.codes.length + ' — use the filter.</div>' : ''); wireRows('[data-vc]', function (tr) { return c.codes.filter(function (x) { return x.code === tr.dataset.vc; })[0]; }, api.saveCode); };
      $('#vc_q').oninput = renderCodes; renderCodes();
      wireRows('[data-ct]', function (tr) { return c.contractors.filter(function (x) { return x.sheet_name === tr.dataset.ct; })[0]; }, api.saveContractor);
      wireRows('[data-ci]', function (tr) { return c.checklist.filter(function (x) { return String(x.id) === tr.dataset.ci; })[0]; }, api.saveChecklistItem);
      if (!canEdit) { rootEl.querySelectorAll('#cqBody input, #cqBody select').forEach(function (el) { if (el.id !== 'vc_q') el.disabled = true; }); return; }
      $('#st_save').onclick = function () { Promise.all([api.saveSetting('inhouse_sample_pct', $('#st_pct').value), api.saveSetting('initial_cutoff', $('#st_cut').value)]).then(function () { toast('Saved'); return load(); }); };
      $('#ct_add').onclick = function () { var n = ($('#ct_new').value || '').trim().toUpperCase(); if (!n) return; api.saveContractor({ sheet_name: n, display_name: n, kind: 'subcon', coverage: 'all', active: true }).then(function () { toast('Added'); load().then(renderSettings); }); };
      $('#ci_add').onclick = function () { var l = ($('#ci_label').value || '').trim(); if (!l) return; api.saveChecklistItem({ section: $('#ci_sec').value, label: l, sort_order: c.checklist.length + 1, active: true, photo_required: false }).then(function () { toast('Added'); load().then(renderSettings); }); };
      $('#st_csvGo').onclick = function () { var f = $('#st_csv').files && $('#st_csv').files[0]; if (!f) { toast('Choose a CSV first'); return; } f.text().then(function (txt) { var rows = parseCsv(txt); if (rows.length < 2) { toast('Empty CSV'); return; } var hdr = rows[0]; var objs = rows.slice(1).map(function (r) { var o = {}; hdr.forEach(function (h, i) { o[h.trim()] = r[i]; }); return o; }); return api.importRows(objs).then(function (r) { toast('Imported ' + r.upserted + ' rows · ' + r.audits_created + ' new audits'); return load().then(renderSettings); }); }).catch(function (e) { toast('Import failed: ' + e.message); }); };
    }
    function wireRows(sel, find, save) { rootEl.querySelectorAll(sel).forEach(function (tr) { tr.querySelectorAll('[data-f]').forEach(function (el) { el.onchange = function () { var row = find(tr); if (!row) return; var prev = row[el.dataset.f]; var v = el.type === 'checkbox' ? el.checked : el.type === 'number' ? (el.value === '' ? null : Number(el.value)) : (el.value === '' ? null : el.value); row[el.dataset.f] = v; save(row).then(function () { toast('Saved ' + (row.code || row.sheet_name || row.label)); }).catch(function (e) { row[el.dataset.f] = prev; if (el.type === 'checkbox') el.checked = !!prev; else el.value = prev == null ? '' : prev; toast('Save failed: ' + e.message); }); }; }); }); }
    function parseCsv(text) { var rows = [], row = [], cell = '', inQ = false, i, ch; text = String(text || ''); for (i = 0; i < text.length; i++) { ch = text[i]; if (inQ) { if (ch === '"') { if (text[i + 1] === '"') { cell += '"'; i++; } else inQ = false; } else cell += ch; } else if (ch === '"') inQ = true; else if (ch === ',') { row.push(cell); cell = ''; } else if (ch === '\n' || ch === '\r') { if (ch === '\r' && text[i + 1] === '\n') i++; row.push(cell); rows.push(row); row = []; cell = ''; } else cell += ch; } if (cell !== '' || row.length) { row.push(cell); rows.push(row); } return rows.filter(function (r) { return r.some(function (c) { return c !== ''; }); }); }

    var TABS = { queue: renderQueue, board: renderBoard, results: renderResults, reports: renderReports, settings: renderSettings };
    if (api.subscribe) S.unsub = api.subscribe(function (e) { var r = e.row || {}; if (r.status === 'done' && r.inspected_at && r.inspected_at.slice(0, 10) === today()) { S.submittedToday++; toast('✅ ' + r.id + ' submitted by ' + (r.inspector || r.assigned_to) + (r.assessment ? ' · ' + r.assessment : '')); if (o.onBadge) o.onBadge(S.submittedToday); } if (S.tab === 'board') loadBoard(); if (S.tab === 'queue') loadQueueStats(); });
    // single fallback timer — realtime is primary
    S.timer = setInterval(function () { if (S.tab === 'board') loadBoard(); else if (S.tab === 'queue') loadQueueStats(); }, 120000);
    load().then(render);
    return { refresh: function () { return load().then(render); }, destroy: function () { if (S.unsub) S.unsub(); clearInterval(S.timer); rootEl.innerHTML = ''; }, badge: function () { return S.submittedToday; }, _S: S, _openDetail: function (id) { openDetail(id); } };
  }
  root.ConsoleQA = { mount: mount };
})(typeof self !== 'undefined' ? self : this);
