#!/usr/bin/env python3
"""Extract QA lookup lists from the QA team's workbook into an additive seed SQL.
Reads ONLY tab 'ACC' lookup columns (no subscriber rows). Usage:
  python3 scripts/qa-extract-seed.py "/Users/alleczandre/Downloads/FOR QA VALIDATION.xlsx"
"""
import re, sys, warnings
warnings.filterwarnings('ignore')
import openpyxl

SRC = sys.argv[1] if len(sys.argv) > 1 else '/Users/alleczandre/Downloads/FOR QA VALIDATION.xlsx'
OUT = 'supabase/migrations/qa-02-seed.sql'

def q(s):
    return "'" + str(s if s is not None else '').replace("'", "''") + "'"

def ws_(s):
    return re.sub(r'\s+', ' ', str(s or '')).strip()

# Penalty text like "OFFENSE LEVEL 1: PHP 500 OFFENSE LEVEL 2: PHP 1,000 OFFENSE LEVEL 3: P2,000"
# -> plain peso amounts per level when present; otherwise NULL (text kept verbatim).
def parse_levels(text):
    out = [None, None, None]
    for m in re.finditer(r'OFFENSE LEVEL\s*(\d)\s*:\s*(.*?)(?=OFFENSE LEVEL\s*\d\s*:|$)', text, flags=re.I):
        lvl = int(m.group(1)); body = m.group(2).strip()
        pm = re.match(r'^(?:FINE OF\s+)?(?:PHP|P|₱)\s*([\d,]+(?:\.\d+)?)(?![\dA-Za-z])', body, flags=re.I)
        if 1 <= lvl <= 3 and pm:
            out[lvl-1] = float(pm.group(1).replace(',', ''))
    return out

wb = openpyxl.load_workbook(SRC, data_only=True)
ws = wb['ACC']
rows = list(ws.iter_rows(values_only=True))
hdr = [ws_(h) for h in rows[0]]

def column(name, nth=0):
    idx = [i for i, h in enumerate(hdr) if h == name][nth]
    return [r[idx] for r in rows[1:] if r[idx] not in (None, '', ' ')]

# violation catalog = the SECOND 'CODE' header block: CODE | TYPE | DESCRIPTION | PENALTY
ci = [i for i, h in enumerate(hdr) if h == 'CODE'][1]
codes = []
for r in rows[1:]:
    if r[ci] in (None, ''):
        continue
    code, typ, desc, pen = [ws_(x) for x in r[ci:ci+4]]
    code = re.sub(r'\s+', '', code)              # "TSU-CO L-002" -> "TSU-COL-002"
    prefix = re.match(r'^[A-Z]+', code)
    codes.append((code, typ, desc, pen, prefix.group(0) if prefix else 'GEN'))

CHECKLIST = [
    ('OUTSIDE', 'Maintenance loop above the NAP', 'PR005'),
    ('OUTSIDE', 'Attachment of S-clamps from every pole', 'PR003'),
    ('PREMISE', 'Attachment of house bracket', 'HA001'),
    ('PREMISE', 'Maintenance loop beside the house bracket', 'PR005'),
    ('PREMISE', 'Layout of drop cable in client premise', 'INW001'),
    ('PREMISE', 'Use of tapping clip and/or tie wrap', 'INW001'),
    ('PREMISE', 'NIU box fixed', 'INW002'),
    ('PREMISE', 'Looping at NIU box', 'INW002'),
    ('PREMISE', 'Patch cord', 'INW002'),
    ('PREMISE', 'Modem location', 'INW002'),
]
CONTRACTORS = [('AHBA', 'AHBA (in-house)', 'inhouse', 'sample')] + [
    (n, n, 'subcon', 'all') for n in ['AVELINE', 'J2', 'RIA', 'MAX - ALLY88', 'JHANRENZ', 'J VANA', 'COMWORKS', 'JD CRUZ']]
QUICK = column('OTHERS')
SETTINGS = [('inhouse_sample_pct', '10'), ('initial_cutoff', '2026-08-01'), ('sync_window_days', '60'),
            ('last_sync_at', ''), ('last_sync_rows', '0')]

known = {c[0] for c in codes}
for _, _, sug in CHECKLIST:
    assert sug in known, 'suggested code missing from catalog: ' + sug

lines = ['-- GENERATED by scripts/qa-extract-seed.py from the QA workbook tab ACC (lookup columns only). Additive; safe to re-run.',
         'begin;']
lines.append('insert into qa.violation_codes(code,category,description,class,severity,penalty_text,penalty_l1,penalty_l2,penalty_l3,active) values')
vals = []
for code, typ, desc, pen, pfx in codes:
    l1, l2, l3 = parse_levels(pen)
    sev = 'CRITICAL' if (l1 or 0) >= 20000 or 'TERMINATION' in pen.upper() or 'CLAWBACK' in pen.upper() else ('MAJOR' if (l1 or 0) >= 1000 else 'MINOR')
    vals.append('(%s,%s,%s,%s,%s,%s,%s,%s,%s,true)' % (q(code), q(typ), q(desc), q(pfx), q(sev), q(pen),
                'null' if l1 is None else l1, 'null' if l2 is None else l2, 'null' if l3 is None else l3))
lines.append(',\n'.join(vals))
lines.append('on conflict (code) do update set category=excluded.category, description=excluded.description, class=excluded.class, severity=excluded.severity, penalty_text=excluded.penalty_text, penalty_l1=excluded.penalty_l1, penalty_l2=excluded.penalty_l2, penalty_l3=excluded.penalty_l3;')

lines.append('insert into qa.checklist_items(section,label,sort_order,active,photo_required,suggested_code) values')
lines.append(',\n'.join('(%s,%s,%d,true,false,%s)' % (q(s), q(l), i+1, q(c)) for i, (s, l, c) in enumerate(CHECKLIST)))
lines.append('on conflict (label) do update set section=excluded.section, sort_order=excluded.sort_order, suggested_code=excluded.suggested_code;')

lines.append('insert into qa.contractors(sheet_name,display_name,kind,coverage,active) values')
lines.append(',\n'.join('(%s,%s,%s,%s,true)' % (q(a), q(b), q(c), q(d)) for a, b, c, d in CONTRACTORS))
lines.append('on conflict (sheet_name) do nothing;')

lines.append('insert into qa.quick_remarks(label,sort_order) values')
lines.append(',\n'.join('(%s,%d)' % (q(ws_(x)), i+1) for i, x in enumerate(QUICK)))
lines.append('on conflict (label) do nothing;')

lines.append('insert into qa.settings(key,value) values')
lines.append(',\n'.join('(%s,%s)' % (q(k), q(v)) for k, v in SETTINGS))
lines.append('on conflict (key) do nothing;')
lines.append('commit;')

open(OUT, 'w', encoding='utf8').write('\n'.join(lines) + '\n')
print('codes=%d checklist=%d contractors=%d quick=%d settings=%d -> %s' % (len(codes), len(CHECKLIST), len(CONTRACTORS), len(QUICK), len(SETTINGS), OUT))
